version: '3'

networks:
    mermaid-etl:
        name: mermaid-etl

volumes:
    mermaid_etl_status_schema:
    mermaid_etl_status_couchdb:

services:

    offline_db:
        container_name: offline_db
        image: couchdb:3.0
        ports:
            - 5984:5984
        volumes:
            - $PWD/couch_data:/opt/couchdb/data
        env_file:
            - .env
        networks:
            - mermaid-etl
    api_db:
        container_name: online_db
        image: kartoza/postgis:13.0
        volumes:
            - $PWD/pg_data:/var/lib/postgresql
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - mermaid-etl
    api_db_migration_monitor:
        container_name: api_db_migration_monitor
        build:
            context: ./api_db_migration_monitor
        depends_on:
            - api_db
        volumes:
            - mermaid_etl_status_schema:/status/schema/
    couchdb_available_monitor:
        container_name: couchdb_available_monitor
        build:
            context: ./couchdb_available_monitor
        depends_on:
            - offline_db
        volumes:
            - mermaid_etl_status_couchdb:/status/couchdb/
    api_db_etl:
        container_name: api_db_etl
        build:
            context: ./api_db_etl
        depends_on:
            - api_db
        volumes:
            - mermaid_etl_status_schema:/status/schema
            - mermaid_etl_status_couchdb:/status/couchdb/
            - ./api_db_etl/app:/app
        networks:
            - mermaid-etl
        env_file: 
            - .env
        ports:
            - 8080:8080
    api_db_pgadmin:
        container_name: api_db_pgadmin
        image: dpage/pgadmin4:4.25
        depends_on:
            - api_db
        ports:
            - 5050:5050
        env_file: 
            - .env
        networks:
            - mermaid-etl